In [2]:
import pandas as pd
import plotly.express as px
from datasets import load_dataset

In [4]:
dataset = load_dataset("DataForGood/climateguard")
df = pd.concat([dataset["train"].to_pandas(), dataset["test"].to_pandas()])
df_fp = df.loc[df.misinformation==False]
df_tp = df.loc[df.misinformation]
display(df_fp.head())
display(df_tp.head())

,label_studio_id,id,day,year,month,start,channel,plaintext,model_name,channel_name,...,misinformation,cards_claims,misinformation_claims,comments,claims,explaination,references,country,prompt_version,pipeline_version
0,1399,0234d6a9618921f044bd648e44eab69bfa6ab60a86fe34...,1,2025,1,2025-01-01T07:48:00+0000,europe1,irréfléchie les marot contre-productive sans j...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,europe1,...,False,"[{'labels': ['6_advocates_are_biased'], 'text'...",[],[],[],[],[],france,None,None
3,1403,4981e5e2c533784c4532d150a0a28be3224309b99c87d9...,1,2025,1,2025-01-01T11:20:00+0000,rtl,personnes malades ou qui travaillent en horair...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,rtl,...,False,[],[],[],[],[],[],france,None,None
5,1407,0348cf0ae599d40c917efd0293c6f25dbe5b35f4b9f632...,2,2025,1,2025-01-02T08:48:00+0000,france24,de nos enfants dans le village on mangeait ce ...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,france24,...,False,[],[],[Duplicata (chunk suivant d'un chunk déjà trai...,[],[],[],france,None,None
6,1411,bb3b0a1b465685f3f0fa4db5abacb69775fc264b6fa8e5...,3,2025,1,2025-01-03T19:36:00+0000,franceinfotv,soigner des des des autres animaux dominique b...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,franceinfotv,...,False,[],[],[],[],[],[],france,None,None
7,1413,36ce95f66260466a978283a181ae0be088073d89bc6de9...,3,2025,1,2025-01-03T05:24:00+0000,itele,baissé de près de cinq pourcent vert qui est o...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,itele,...,False,[],[],[],[],[],[],france,None,None

,label_studio_id,id,day,year,month,start,channel,plaintext,model_name,channel_name,...,misinformation,cards_claims,misinformation_claims,comments,claims,explaination,references,country,prompt_version,pipeline_version
1,1400,7931b61f0a7b075005be7fa688d27dc947799486f1d1f8...,1,2025,1,2025-01-01T10:58:00+0000,europe1,trente ans est amorti depuis longtemps dans la...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,europe1,...,True,[{'labels': ['4_solutions_are_ineffective_or_h...,"[{'labels': ['misinformation'], 'text': 'vous ...",[],[Une voiture ancienne bien entretenue pollue m...,[],[],france,None,None
2,1401,ad748664164e2d83fb9c539f52ac07153a2d85bdfa4884...,1,2025,1,2025-01-01T21:32:00+0000,itele,incompétence quelques bien sûr il y a une inco...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,itele,...,True,"[{'labels': ['6_advocates_are_biased'], 'text'...","[{'labels': ['misinformation'], 'text': 'On no...",[],[Les gouvernements démocrates affirment que le...,[],[],france,None,None
4,1404,af40a529984231434e6d2c5f5f0c4a73fc7bbb152550db...,2,2025,1,2025-01-02T21:58:00+0000,bfmtv,c notamment la qu' il est décidé par exemple d...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,bfmtv,...,True,"[{'labels': ['2_humans_are_not_the_cause'], 't...","[{'labels': ['misinformation'], 'text': 'qu'il...",[],[Depuis la baisse du soutien au nucléaire au p...,[],[],france,None,None
8,1414,eccac846d72334c31024df8b89363ebd86d78244586bc1...,3,2025,1,2025-01-03T08:48:00+0000,itele,est indispensable mais on procédant ainsi de f...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,itele,...,True,[],[],[Je supprimerais cette phrase car elle n'est p...,[],[],[],france,None,None
12,1421,9b24bcf358697fc3477d3c99e736c3f0791b39faaa552d...,3,2025,1,2025-01-03T10:40:00+0000,sud-radio,cours sur le leasing social où il y a eu vingt...,ft:gpt-4o-mini-2024-07-18:personal::B1xWiJRm,sud-radio,...,True,[{'labels': ['4_solutions_are_ineffective_or_h...,"[{'labels': ['misinformation'], 'text': 'la tr...",[1],[Le raccordement des moyens de production d'él...,[],[],france,None,None

In [18]:
import plotly.graph_objects as go
df_counts_channel = pd.merge(
    df_fp.groupby(["channel"]).agg(counts_fp=("id", "count")),
    df_tp.groupby(["channel"]).agg(counts_tp=("id", "count")),
    left_index=True,
    right_index=True,
    how="outer",
).fillna(0)


px.bar(
    df_counts_channel,
    y=["counts_fp", "counts_tp"],
    barmode="group",
)

In [38]:
df_counts_channel_program = pd.merge(
    df_fp.groupby(["channel_program"]).agg(counts_fp=("id", "count")),
    df_tp.groupby(["channel_program"]).agg(counts_tp=("id", "count")),
    left_index=True,
    right_index=True,
    how="outer",
).fillna(0)

In [39]:
df_counts_channel_program["counts"] = df_counts_channel_program[["counts_fp", "counts_tp"]].sum(axis=1)
df_counts_channel_program.describe()

        counts_fp   counts_tp       counts
count   60.000000   60.000000    60.000000
mean    21.816667   11.533333    33.350000
std    104.207338   52.274525   156.168078
min      0.000000    0.000000     1.000000
25%      1.000000    0.000000     1.750000
50%      3.500000    1.000000     4.500000
75%     12.250000    5.000000    16.250000
max    811.000000  402.000000  1213.000000

In [40]:
df_counts_channel_program_significant = df_counts_channel_program.loc[df_counts_channel_program.counts >= 10]

In [41]:
df_counts_channel_program_significant.loc["Other"] = df_counts_channel_program.loc[df_counts_channel_program.counts < 10].sum(axis=0).copy()

/var/folders/_y/jjyv0bm5597_x15dvpxnsmrc0000gn/T/ipykernel_43255/3746614938.py:1: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

In [42]:
df_counts_channel_program_significant

                               counts_fp  counts_tp  counts
channel_program
                                    25.0        5.0    30.0
 Europe 1 Matin Week-end             5.0        7.0    12.0
28 minutes                          16.0        5.0    21.0
Apolline Matin                      20.0        8.0    28.0
Bonjour                              6.0        6.0    12.0
Bonjour ! La Matinale               13.0        3.0    16.0
Estelle Midi                        23.0       22.0    45.0
Europe 1 Matin                      44.0       23.0    67.0
Information en continu             811.0      402.0  1213.0
JT 20h + météo                      12.0        3.0    15.0
L'heure des pros                     6.0       20.0    26.0
Le 7/10                             16.0        1.0    17.0
Le Grand Matin                      34.0       27.0    61.0
Le Grand Matin Week-end              7.0        8.0    15.0
Les grandes gueules                 51.0       27.0    78.0
Les matins                          17.0        1.0    18.0
Mettez-vous d'accord                27.0       16.0    43.0
Pascal Praud et vous                10.0       15.0    25.0
Punchline                           10.0        4.0    14.0
RTL Bonsoir                          7.0        4.0    11.0
RTL Matin                           13.0        1.0    14.0
Soir                                12.0        8.0    20.0
Sud Radio dans tous ses états       36.0       62.0    98.0
Télématin                           14.0        2.0    16.0
Other                               74.0       12.0    86.0

In [45]:
px.bar(
    df_counts_channel_program_significant,
    y=["counts_fp", "counts_tp"],
    barmode="group",
    log_y=True,
)

In [54]:
import asyncio
import ast
from pydantic import BaseModel
from openai import AsyncClient

async_client = AsyncClient()


class TranscriptType(BaseModel):
    number_of_speakers: int
    conversation_type: str

async def get_discussion_type(idx, transcript, semaphore=None):
    if semaphore:
        await semaphore.acquire()
    try:
        chat_response = await async_client.responses.parse(
            model="gpt-5-nano",
            reasoning={"effort": "minimal"},
            #temperature=0,
            input=[{"role": "developer", "content": "You are an assistant helping editors to aggregate tv transcripts into categories of debate and monologue."},
                {
                    "role": "user",
                    "content": f"""
                            Given a transcript from a tv or radio program, it is your duty to determine whether the transcript contains a monologue or a debate.
                            A monologue is when only one speaker can be identified and a debate is when two or more speakers are identified.

                            Transcript: {transcript}
                            Return the answer in json format with the keys 'number_of_speakers' and 'conversation_type', where conversation_type
                            is one of debate and monologue.
                            """
                },
            ],
            text_format=TranscriptType,
        )
    finally:
        if semaphore:
            semaphore.release()
    try:
        return idx, ast.literal_eval(chat_response.output_text)
    except SyntaxError:
        return idx, str(chat_response.output_text)

In [55]:
await get_discussion_type(0, df.plaintext[0])

(0, {'number_of_speakers': 2, 'conversation_type': 'debate'})

In [ ]:
from tqdm.asyncio import tqdm

semaphore = asyncio.Semaphore(20)
tasks = [
    get_discussion_type(
        idx,
        row["plaintext"],
        semaphore=semaphore
    ) for idx, row in df_fp.reset_index().iterrows()
]
conv_results_fp = await tqdm.gather(*tasks)

100%|██████████| 1309/1309 [01:23<00:00, 15.69it/s]

In [68]:
conv_results_fp = sorted(conv_results_fp, key=lambda x: x[0])

In [74]:
conv_results_fp_df = pd.DataFrame([record[1] for record in conv_results_fp])
df_fp = pd.concat([df_fp.reset_index(), conv_results_fp_df], axis=1)

In [77]:
semaphore = asyncio.Semaphore(20)
tasks = [
    get_discussion_type(
        idx,
        row["plaintext"],
        semaphore=semaphore
    ) for idx, row in df_tp.reset_index().iterrows()
]
conv_results_tp = await tqdm.gather(*tasks)
conv_results_tp = sorted(conv_results_tp, key=lambda x: x[0])
conv_results_tp_df = pd.DataFrame([record[1] for record in conv_results_tp])
df_tp = pd.concat([df_tp.reset_index(), conv_results_tp_df], axis=1)

100%|██████████| 692/692 [00:40<00:00, 17.15it/s]

In [78]:
df_conv_type = pd.merge(
    df_fp.groupby("conversation_type").agg(counts_fp=("id", "count")),
    df_tp.groupby("conversation_type").agg(counts_tp=("id", "count")),
    left_index=True,
    right_index=True,
)

In [81]:
px.bar(df_conv_type, y=["counts_fp", "counts_tp"], barmode="group")

In [91]:
df_fp["hour"] = pd.to_datetime(df_fp.start).dt.tz_convert('Europe/Paris').dt.hour
df_tp["hour"] = pd.to_datetime(df_tp.start).dt.tz_convert('Europe/Paris').dt.hour

df_hour = pd.merge(
    df_fp.groupby("hour").agg(counts_fp=("id", "count")),
    df_tp.groupby("hour").agg(counts_tp=("id", "count")),
    left_index=True,
    right_index=True,
)
px.bar(df_hour, y=["counts_fp", "counts_tp"], barmode="group")

In [92]:
df_fp["weekday"] = pd.to_datetime(df_fp.start).dt.tz_convert('Europe/Paris').dt.weekday
df_tp["weekday"] = pd.to_datetime(df_tp.start).dt.tz_convert('Europe/Paris').dt.weekday

df_hour = pd.merge(
    df_fp.groupby("weekday").agg(counts_fp=("id", "count")),
    df_tp.groupby("weekday").agg(counts_tp=("id", "count")),
    left_index=True,
    right_index=True,
)
px.bar(df_hour, y=["counts_fp", "counts_tp"], barmode="group")